### PR TITLE
fix(KvCheckbox): Allow checkboxes to use an array in v-model

### PR DESCRIPTION
**Pull request by ryan-ludwig**
VUE-715

### CODE REVIEW

**Comment by ryan-ludwig** [comment]
Allows for binding multiple checkboxes to the same array, like 
https://vuejs.org/v2/guide/forms.html#Checkbox

**Review by mcstover — APPROVED** [review]
A little ;) more code to support watching both but looks right.

**Review by BoulderBrains — APPROVED** [review]

**Review by eddieferrer — APPROVED** [review]
👍

**Review by emuvente — APPROVED** [review]
Nice!

**Pull request merged**
