### PR TITLE
VUE-591: KvMaterialIcon, alternate version

### PR DESCRIPTION
**Pull request by ryan-ludwig**
This version imports SVG path data from a material icons library. You pass then pass the path data as a prop to KvMaterialIcon component which renders the SVG.

This is in contrast to #40 which imports SFC Vue Components.

The way you set color and size is the same (tailwind classes).

### CODE REVIEW

**Comment by ryan-ludwig** [comment]
I think this PR is much more likely to be tree shaken compared to #40. However, I'm not convinced #40 won't be tree-shaken.

This version does spin up storybook much faster.

For either of these PRs we'll need to do webpack bundle analyzing on UI to make sure we're not loading up the 100s of icons in Material Design in a production build.

**Comment by eddieferrer** [comment]
I agree with you, I think this will get tree shaken and is a more efficient approach than #40 

Can we find a way to add the control dropdown back to the story, so that via storybook you can see what all the icons look like? I'm not sure there is a programatic way to do this, but maybe just a file? Some ideas here: https://github.com/google/material-design-icons/issues/241

**Comment by mcstover** [comment]
@eddieferrer @ryan-ludwig There are over 5k icons in mdi so I think we probably just need to continue with the approach of building out the "Common" story with icons we see showing up in our designs. Maybe add a link in this story somewhere out to the mdi visual index.

Otherwise, how are you all feeling about this approach which requires a little more work in that the specific icon needs to be imported before use? I don't really mind that and like the more specific usage and implementation.

**Review by mcstover — APPROVED** [review]

**Review by eddieferrer — APPROVED** [review]

**Comment by eddieferrer** [comment]
I'm fine with this approach 👍

**Review by BoulderBrains — APPROVED** [review]

**Comment by ryan-ludwig** [comment]
@eddieferrer I made a story that looped and displayed all the exported icons from the @mdi/js package. My browser nearly gave up. Probably best to browse and filter from https://materialdesignicons.com/ (though I don't know how they pulled it off)

**Pull request merged**
