### PR TITLE
misc Safari fixes

### PR DESCRIPTION
**Pull request by ryan-ludwig**
Will need to get these changes into the vue3 branch as well

### CODE REVIEW

**Review by mcstover — APPROVED** [review]
Does this address the sometimes giant icons in the loan card CTA?

**Comment by ryan-ludwig** [comment]
> Does this address the sometimes giant icons in the loan card CTA?

@mcstover No, but that's likely the same issue of not having a width or height set on the `<kv-material-icon>`. Chrome and Firefox keep the svg icon at it's default size, but Safari makes it really big if you don't set `<kv-material-icon class="tw-w-3" />`

**Review by roger-in-kiva — APPROVED** [review]
Great!

**Review by emuvente — APPROVED** [review]
👍

**Pull request merged**
