### PR TITLE
feat: kvswitch component was rewritten using composition api

### PR DESCRIPTION
**Pull request by roger-in-kiva**
kvswitch component was rewritten using composition api

### CODE REVIEW

**Review by emuvente — COMMENTED** [review]
For this to work with v-model in Vue3, I think we need to rename the `checked` prop to be `modelValue`, and rename the `change` event to be `update:modelValue`. We would also need to change the model option so that Vue 2 picks up the changed names:
```
model: {
	prop: 'modelValue',
	event: 'update:modelValue',
},
```
Some of the stories may need to be updated for this component as well, so that they listen to the `update:modelValue` event instead of the `change` event.

**Comment by roger-in-kiva** [comment]
> 

This means that the without V-Model option in storybook should be removed?

**Comment by emuvente** [comment]
> This means that the without V-Model option in storybook should be removed?

I think we can keep that to demonstrate how it can be used with without v-model. The story template would have these lines removed:
```
:checked="switchExampleModel"
@change="(val) => switchExampleModel = val"
```
and replaced with:
```
:modelValue="switchExampleModel"
@update:modelValue="(val) => switchExampleModel = val"
```

**Comment by roger-in-kiva** [comment]
> update:modelValue

Nice Suggestion, the feature was added.

**Comment by emuvente** [comment]
This looks good to go! Thanks for making those updates!

I added some tests to check attribute and v-model behavior, and a fix for the attribute test failures so that it can be used for other components.

**Review by emuvente — APPROVED** [review]

**Review by mcstover — APPROVED** [review]

**Review by ryan-ludwig — APPROVED** [review]

**Pull request merged**
