### PR TITLE
fix: side sheet shouldn't be full height

### PR DESCRIPTION
**Pull request by dyersituations**
https://kiva.atlassian.net/browse/MP-1211

### CODE REVIEW

**Review by mcstover — APPROVED** [review]
Guessing this prevents the side sheet from extending to the full height of it's contents. Seems like it should match the viewport height then allow scrolling within...

**Comment by dyersituations** [comment]
> Guessing this prevents the side sheet from extending to the full height of it's contents. Seems like it should match the viewport height then allow scrolling within...

It's a bit complicated because of the space for the header. In testing locally, removing this full height was a decent compromise. The sheet doesn't expand forever if the parent to larger, and the content is scrollable if the parent is smaller.

**Comment by roger-in-kiva** [comment]
We could probably have new loans with no lenders and no teams sections. Said that side sheet could be smaller than viewport for large screens... agree having viewport height as min height for side sheet.

**Comment by dyersituations** [comment]
> We could probably have new loans with no lenders and no teams sections. Said that side sheet could be smaller than viewport for large screens... agree having viewport height as min height for side sheet.

The problem again is the nav bar, we could add JS to dynamically work with the header sizing, and maybe we'll need to do that eventually. This solution seems to be a decent compromise when I test it locally.

**Review by roger-in-kiva — APPROVED** [review]

**Pull request merged**
